IF NOT EXISTS (SELECT name FROM sys.tables WHERE name = 'StradivariusSales')
	CREATE TABLE [dbo].[StradivariusSales](
	[SaleStamp] [char](25) NOT NULL,
	[Year] [numeric](4, 0) NOT NULL,
	[Number] [numeric](10, 0) NOT NULL,
	[Date] [date] NOT NULL,
	[Customer_Number] [numeric](10, 0) NOT NULL,
	[Customer_Name] [varchar](55) NOT NULL,
	[Customer_TaxpayerNumber] [varchar](20) NOT NULL,
	[Customer_Balance] [numeric](19, 6) NOT NULL,
	[Customer_Fax] [varchar](60) NOT NULL,
	[Customer_Phone] [varchar](60) NOT NULL,
	[Customer_Contact] [varchar](30) NOT NULL,
	[Customer_Address] [varchar](55) NOT NULL,
	[Customer_ZipCode] [varchar](45) NOT NULL,
	[Customer_Location] [varchar](43) NOT NULL,
	[Customer_Type] [varchar](20) NOT NULL,
	[Customer_DueDays] [numeric](3, 0) NOT NULL,
	[Customer_Plafond] [numeric](19, 6) NOT NULL,
	[Customer_BanckAccountNumber] [varchar](28) NOT NULL,
	[Customer_Segment] [varchar](25) NOT NULL,
	[Customer_Email] [varchar](45) NOT NULL,
	[Customer_Mobile] [varchar](45) NOT NULL,
	[EmployeeNumber] [numeric](6, 0) NOT NULL,
	[Seller_Number] [numeric](4, 0) NOT NULL,
	[Seller_FullName] [varchar](40) NOT NULL,
	[Seller_ShortName] [varchar](20) NOT NULL,
	[Seller_Address] [varchar](40) NOT NULL,
	[Seller_ZipCode] [varchar](28) NOT NULL,
	[Seller_Location] [varchar](43) NOT NULL,
	[Seller_Phone] [varchar](60) NOT NULL,
	[Seller_Email] [varchar](45) NOT NULL,
	[PaymentDate] [date] NOT NULL,
	[Currency] [char](20) NOT NULL,
	[ProductsGrossValue] [numeric](19, 6) NULL,
	[DiscountTotal] [numeric](19, 6) NOT NULL,
	[Freight] [numeric](19, 6) NOT NULL,
	[ValueForVATIncidence] [numeric](19, 6) NOT NULL,
	[VATTotal] [numeric](19, 6) NOT NULL,
	[TotalValue] [numeric](19, 6) NOT NULL,
	[TotalCostPrices] [numeric](19, 6) NULL,
	[CreationDate] [date] NOT NULL,
	[LastUpdateDate] [date] NOT NULL)
ELSE 
	TRUNCATE TABLE StradivariusSales