IF NOT EXISTS (SELECT name FROM sys.tables WHERE name = 'StradivariusProducts')
	CREATE TABLE [dbo].[StradivariusProducts](
	[Reference] [char](18) NOT NULL,
	[Description] [char](60) NOT NULL,
	[ProductFamily] [char](60) NOT NULL,
	[Stock] [numeric](13, 3) NOT NULL,
	[UnitPrice] [numeric](19, 6) NOT NULL,
	[OrderPoint] [numeric](10, 3) NOT NULL,
	[Supplier_Number] [numeric](10, 0) NOT NULL,
	[Supplier_Name] [varchar](55) NOT NULL,
	[Supplier_Fax] [varchar](60) NOT NULL,
	[Supplier_Phone] [varchar](60) NOT NULL,
	[Supplier_Contact] [varchar](30) NOT NULL,
	[Supplier_Address] [varchar](55) NOT NULL,
	[Supplier_ZipCode] [varchar](45) NOT NULL,
	[Supplier_TaxpayerNumber] [varchar](20) NOT NULL,
	[Supplier_Type] [varchar](20) NOT NULL,
	[Supplier_Discount] [numeric](5, 2) NOT NULL,
	[Supplier_DueDays] [numeric](3, 0) NOT NULL,
	[Supplier_ContactJob] [varchar](15) NOT NULL,
	[Supplier_Email] [varchar](45) NOT NULL,
	[Supplier_Nationality] [varchar](20) NOT NULL,
	[Supplier_Mobile] [varchar](45) NOT NULL,
	[Supplier_Balance] [numeric](19, 6) NOT NULL,
	[Supplier_Plafond] [numeric](19, 6) NOT NULL,
	[Supplier_Class] [varchar](30) NOT NULL,
	[MinimumStock] [numeric](13, 3) NOT NULL,
	[StartSellingDate] [date] NOT NULL,
	[ProductCategory] [varchar](50) NOT NULL,
	[Classification] [varchar](20) NOT NULL,
	[CostPrice] [numeric](19, 6) NOT NULL,
	[CaptiveQuantity] [numeric](13, 3) NOT NULL,
	[VATRate] [numeric](2, 0) NOT NULL,
	[CreationDate] [date] NOT NULL,
	[LastUpdateDate] [date] NOT NULL)
ELSE 
	TRUNCATE TABLE StradivariusProducts