IF NOT EXISTS (SELECT name FROM sys.tables WHERE name = 'DimMoney')
BEGIN
	CREATE TABLE [dbo].[DimMoney](
		[MoneyKey] [int] IDENTITY(1,1) NOT NULL,
		[MoneyID] [char](20) NOT NULL,
		[Description] [varchar](55) NOT NULL,
		[Abbreviation] [varchar](55) NOT NULL,
	 CONSTRAINT [PK_DimMoney] PRIMARY KEY CLUSTERED 
	(
		[MoneyKey] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [NonClusteredIndex-MoneyID] ON [dbo].[DimMoney]
	(
		[MoneyID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END